-- Run this file once in the SQL Editor of a NEW, EMPTY Supabase project.
-- Recreates the tables used by the current portal's auth/profile integration.
-- Do not also run the historical v1/v2 migrations or rls-setup.sql.
BEGIN;

CREATE TABLE public.roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);
-- IDs also match the portal's legacy numeric role mapping.
INSERT INTO public.roles (name) VALUES ('admin'), ('manager'), ('employee'), ('hr'), ('finance');

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email varchar(150) NOT NULL UNIQUE,
  first_name varchar(100),
  last_name varchar(100),
  role_id bigint NOT NULL DEFAULT 3 REFERENCES public.roles(id),
  avatar_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  type varchar(50),
  title varchar(255) NOT NULL,
  message text,
  is_read boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.office_location_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id integer NOT NULL,
  office_location_id integer,
  is_current boolean DEFAULT true,
  effective_from date NOT NULL,
  effective_to date,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_location_history ENABLE ROW LEVEL SECURITY;

CREATE FUNCTION public.is_admin() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p JOIN public.roles r ON r.id = p.role_id
    WHERE p.id = (SELECT auth.uid()) AND p.is_active AND r.name = 'admin'
  );
$$;
REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- Limit browser writes to editable profile fields. Roles, activity and email
-- are managed via the trusted backend/dashboard, never by a browser user.
REVOKE ALL ON public.roles, public.profiles, public.notifications,
  public.office_location_history FROM anon, authenticated;
GRANT SELECT ON public.roles, public.profiles, public.notifications TO authenticated;
GRANT UPDATE (first_name, last_name, avatar_url) ON public.profiles TO authenticated;
GRANT UPDATE (is_read) ON public.notifications TO authenticated;
GRANT ALL ON public.roles, public.profiles, public.notifications,
  public.office_location_history TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.roles_id_seq,
  public.notifications_id_seq, public.office_location_history_id_seq TO service_role;

CREATE POLICY roles_read ON public.roles FOR SELECT TO authenticated USING (true);
CREATE POLICY profiles_read ON public.profiles FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = id OR (SELECT public.is_admin()));
CREATE POLICY profiles_update ON public.profiles FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = id OR (SELECT public.is_admin()))
  WITH CHECK ((SELECT auth.uid()) = id OR (SELECT public.is_admin()));
CREATE POLICY notifications_read ON public.notifications FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);
CREATE POLICY notifications_update ON public.notifications FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = user_id) WITH CHECK ((SELECT auth.uid()) = user_id);
-- office_location_history has no browser policies: only trusted server access.

CREATE FUNCTION public.handle_new_user() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, first_name, last_name, role_id)
  VALUES (
    NEW.id, NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'first_name', split_part(NEW.raw_user_meta_data->>'full_name', ' ', 1)),
    COALESCE(NEW.raw_user_meta_data->>'last_name', split_part(NEW.raw_user_meta_data->>'full_name', ' ', 2)),
    (SELECT id FROM public.roles WHERE name = 'employee')
  );
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE FUNCTION public.touch_profile_updated_at() RETURNS trigger
LANGUAGE plpgsql SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.touch_profile_updated_at() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.touch_profile_updated_at();

COMMIT;
